### ISSUE TITLE
Ship `--use-submission-api` feature

### ISSUE THREAD

**Issue by eviljeff** [mozilla/web-ext#2503]
#2451 added support for signing add-ons via addons.mozilla.org/api/v5/addons/addon/ api endpoints (aka addon submission api), which an experimental `--use-submission-api`.  Before it's released (or perhaps publicized, if it's released earlier) there are some features missing if it's to be a complete solution for submitting listed add-ons to AMO:

P1 Blockers
- [x] #2487 - needed to provide complete metadata for the first listed version of an add-on
- [x] #2490 - needed to allow subsequent versions to be uploaded easily.
- [x] #2491 - needed to allow subsequent versions to be uploaded easily. (first listed version will often be delayed for 24 hours, and the signing will timeout long before that, meaning we won't capture the add-on id for subsequent versions.)
- [x] #2504 - need for consistent option naming.

P2 Blockers
- [ ] #2497 - useful to allow source files to be provided for obfuscated xpis
- [x] #2472 - useful for users who need to use a proxy. 
- [x] #2492 - useful for efficiency, now there are significantly more metadata validation requirements at the create stage for the first listed version of an add-on

**Comment by rpl** [comment]
@eviljeff would you mind to add also #2504 to the P1s?

During the triage today we also discussed about the issue listed in this tracking meta and what would be considered blocking for which phase and the following is a more detailed summary of the outcome of that discussion:

- #2504 would be the only one we would consider blocking to release a new version of web-ext which introduce the new `--use-submission-api` option
- all the P1s in this issue to be blocking for highlighting the feature more broadly (e.g. through a blogpost)
- #2472 would be blocking for considering the previous implementation deprecated and ready for removal
